# Generated by Django 5.0.4 on 2024-05-27 10:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadleave_metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670))),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='static/excel_folder/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UploadLeave Metadata',
                'verbose_name_plural': 'UploadLeave Metadata',
            },
        ),
        migrations.RemoveField(
            model_name='leave_metadata',
            name='excel_file',
        ),
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 16, 56, 766670)),
        ),
        migrations.AddField(
            model_name='leave_metadata',
            name='upload_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_app.uploadleave_metadata'),
        ),
    ]
