# Generated by Django 5.0.4 on 2024-05-30 11:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0012_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_detail_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533))),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Project Detail Model',
                'verbose_name_plural': 'Project Detail Model',
            },
        ),
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 17, 21, 16, 499533)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_app.project_detail_model'),
        ),
    ]
