# Generated by Django 5.0.4 on 2024-07-12 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0013_project_detail_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_app.department_metadata'),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_app.country_metadata'),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 17, 31, 52, 626519)),
        ),
    ]
