# Generated by Django 4.0.3 on 2024-11-12 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0016_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 30, 34, 187265)),
        ),
    ]
