# Generated by Django 4.0.3 on 2024-11-19 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0017_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 13, 26, 35, 288454)),
        ),
    ]
