# Generated by Django 4.0.3 on 2025-03-11 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0022_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.RemoveField(
            model_name='employee_metadata',
            name='work_location',
        ),
        migrations.AddField(
            model_name='employee_metadata',
            name='work_location',
            field=models.ManyToManyField(blank=True, to='leave_app.country_metadata'),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 38, 24, 227159)),
        ),
    ]
