# Generated by Django 4.0.3 on 2025-03-17 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0023_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770)),
        ),
        migrations.CreateModel(
            name='email_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2025, 3, 17, 13, 15, 43, 804770))),
                ('email_send_to', models.TextField()),
                ('subject', models.CharField(max_length=150)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('remainder', models.IntegerField(default=0)),
                ('email_send', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('leave_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.leave_metadata')),
            ],
            options={
                'verbose_name': 'Email Model',
                'verbose_name_plural': 'PEmail Model',
            },
        ),
    ]
