# Generated by Django 4.0.3 on 2025-03-18 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0024_alter_country_metadata_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email_model',
            options={'verbose_name': 'Email Model', 'verbose_name_plural': 'Email Model'},
        ),
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771)),
        ),
        migrations.CreateModel(
            name='department_head_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2025, 3, 18, 17, 1, 37, 649771))),
                ('department', models.ManyToManyField(blank=True, to='leave_app.department_metadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Head Model',
                'verbose_name_plural': 'Department Head Model',
            },
        ),
        migrations.AddField(
            model_name='email_model',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_app.department_head_model'),
        ),
    ]
