# Generated by Django 5.0.6 on 2025-06-26 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0025_alter_email_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='department_head_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='department_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='employee_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='holiday_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='indirectsupervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='leave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='project_detail_model',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='supervisor_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
        migrations.AlterField(
            model_name='uploadleave_metadata',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 14, 13, 38, 868500)),
        ),
    ]
